name: rexroth-tpm2-webserver
base: core18
version: '0.0.1'
summary: A snap containing a tpm2 based openssl server
description: |
  Providing an example for TPM2 usage.

grade: devel
confinement: strict

plugs:
  tpm2-socket:
    interface: content
    content: tpm2-socket
    target: $SNAP_DATA/tpm2-socket
  system-configuration:
    interface: content
    content: system-configuration
    target: $SNAP_DATA/system-configuration
slots:
  package-certificates:
    interface: content
    content: package-certificates
    source:
      write:
      - $SNAP_COMMON/package-certificates/${SNAPCRAFT_PROJECT_NAME}
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}

parts:
  configs:
    plugin: dump
    source: ./configs
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/
  tpm2-tools:
    plugin: autotools
    build-environment:
      - LDFLAGS: "$LDFLAGS -Wl,-rpath-link,$SNAPCRAFT_STAGE/lib"
    source: https://github.com/tpm2-software/tpm2-tools
    source-type: git
    source-tag: "5.0"
    build-packages:
    - pandoc
    - pkg-config
    - to amd64:
      - autoconf
      - autoconf-archive
      - libcmocka-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libtool
      - uuid-dev
    - to arm64:
      - autoconf
      - autoconf-archive
      - libcmocka-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libtool
      - uuid-dev
    stage-packages:
    - to amd64:
      - libasn1-8-heimdal
      - libcurl4
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      - libroken18-heimdal
      #- librtmp1
      #- libsasl2-2
      - libwind0-heimdal
      - libuuid1
    - to arm64:
      - libasn1-8-heimdal
      - libcurl4
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      - libroken18-heimdal
      #- librtmp1
      #- libsasl2-2
      - libwind0-heimdal
      - libuuid1
    prime:
      - -include
    after:
      - tpm2-tss

  tpm2-tss:
    plugin: autotools
    source: https://github.com/tpm2-software/tpm2-tss
    source-type: git
    source-tag: 3.0.3
    build-packages:
    - gcc
    - g++
    - doxygen
    - pkg-config
    - to amd64:
      - autoconf
      - autoconf-archive
      - libtool
      - libltdl-dev
      - libjson-c-dev
      - libgcrypt20-dev
      - liburiparser-dev
      - libcurl4-openssl-dev
      - libssl-dev
    - to arm64:
      - autoconf
      - autoconf-archive
      - libtool
      - libltdl-dev
      - libjson-c-dev
      - libgcrypt20-dev
      - liburiparser-dev
      - libcurl4-openssl-dev
      - libssl-dev
    stage-packages:
      - to amd64:
        - libgcrypt20
        - libssl1.1
        - libgpg-error0
        - libjson-c3
        - libcurl4
      - to arm64:
        - libgcrypt20
        - libssl1.1
        - libgpg-error0
        - libjson-c3
        - libcurl4
    prime:
      - -include

  tpm2-tss-engine:
    plugin: autotools
    build-environment:
      - LDFLAGS: "$LDFLAGS -Wl,-rpath-link,$SNAPCRAFT_STAGE/lib"
    source: https://github.com/tpm2-software/tpm2-tss-engine
    source-type: git
    source-branch: "master"
    build-packages:
      - pandoc
      - pkg-config
      - gcc
      - to amd64:
        - autoconf
        - autoconf-archive
        - libtool
        - libssl-dev
      - to arm64:
        - autoconf
        - autoconf-archive
        - libtool
        - libssl-dev
    after:
      - tpm2-tss

  webserver:
    plugin: dump
    source: webserver
    organize:
      tpm2-webserver.sh: usr/bin/tpm2-webserver.sh

apps:
  rexroth-tpm2-webserver:
    command: usr/bin/tpm2-webserver.sh
    daemon: simple
    restart-condition: always
    restart-delay: 5s
    plugs: [tpm2-socket, system-configuration, network, network-bind]
