name: sdk-py-webserver
version: 1.0.2
summary: Webserver Sample written in Python for ctrlX
#title: sdk-py-webserver
description: |
  This sample shows how to create a webserver app in ctrlX
base: core18
confinement: strict
grade: stable

apps:
  webserver:
    command: main.py
    plugs:
      - network-bind
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s 

parts:
  webserver:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - ../../whl/ctrlx_datalayer-1.3.0-py3-none-any.whl
      - ../../whl/ctrlx_fbs-1.0.0-py3-none-any.whl
      - flatbuffers~=1.12
      - PyJWT

  configs:
    plugin: dump
    source: ./configs
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

  www:
    plugin: dump
    source: ./www


slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
      - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}

plugs:
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
