# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-automationbundle
version: "2.0.0"
grade: stable
summary: Sample Snap for providing simple bundle and motion
description: |
  This app will provide a simple automation framework bundle and shows motion accesses.
base: core20
confinement: strict

#  describes how to import, and potentially build, each required part of the snap:
parts:
  bundle:
    source: ./generated/automation-bundle
    plugin: dump
    organize:
     '*' : automation-bundle-v2/${SNAPCRAFT_PROJECT_NAME}/

slots:
  automation-bundle-v2:
    interface: content
    content: automation-bundle-v2
    source:
      read:
        - $SNAP/automation-bundle-v2/${SNAPCRAFT_PROJECT_NAME}