name: sdk-py-logbook
version: 2.3.0
summary: Logbook sample written in Python for ctrlX
title: sdk-py-logbook
description: |
  This sample shows how to log with different loglevels
base: core20
confinement: strict
grade: stable

apps:
  logbook:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 

parts:
  logbook:
    plugin: python
    source: .

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
