name: sdk-py-datalayer-provider-alldata
version: 1.0.1
summary: All data provider sample written in Python for ctrlX
#title: sdk-py-datalayer-provider-alldata
description: |
  This sample shows a Data Layer provider which is publishing nodes of all data types
base: core18
confinement: strict
grade: stable

apps:
  provider:
    command: main.py
    plugs:
      - network
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 

parts:
  provider:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - ../../whl/ctrlx_datalayer-1.3.0-py3-none-any.whl
      - ../../whl/ctrlx_fbs-1.0.0-py3-none-any.whl
      - flatbuffers~=1.12

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
