# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: datalayerclient
version: "1.0.0"
grade: stable
summary: Sample app for datalayer client
description: |
  This app will modify values of 'myData' node provider  
  on Datalayer (requires sample app 'registernode')
base: core18
confinement: strict

# define how apps & services are exposed to host system
apps:
  datalayerClient:
    command: datalayerClient
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs: [network]
    daemon: simple
    passthrough:
      restart-condition: on-failure
      restart-delay: 5s 

parts:
  datalayerclient:
    plugin: dump
    source: ./generated/build

  #flatbuffers:
  #  plugin: dump
  #  source: ./bfbs

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
