name: sdk-py-calc
version: 2.1.0
summary: Makes a calculation in Python
title: SDK Python Calculation Sample
description: 'Sample App in Python using Data Layer subscriptions
'
base: core20
confinement: strict
grade: stable

apps:

  client:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

parts:

  client:
    plugin: python
    source: .

  datalayerdeb:
    plugin: dump
    source: ./tmp/ctrlx-datalayer.deb
    source-type: deb
    stage-packages:
      - libzmq5
    override-pull: |
      mkdir -p ../../../tmp/
      cp ../../../../../deb/ctrlx-datalayer-1.*.*.deb ../../../tmp/ctrlx-datalayer.deb
      snapcraftctl pull
    override-prime: |
      rm -rf ../tmp
      snapcraftctl prime
      
# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
