name: sdk-py-calc
version: 2.0.0
summary: Makes a calculation in Python
title: SDK Python Calculation Sample
description: 'Sample App in Python using Data Layer subscriptions
'
base: core20
confinement: strict
grade: stable

apps:

  client:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

parts:

  client:
    plugin: python
    source: .

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
