name: sdk-py-client-light
version: 2.0.0
summary: Data Layer client sample written in Python for ctrlX.
title: sdk-py-client-light
description: |
  The sample demonstrates how to read values from ctrlX Data Layer tree and write out the values to console. 
base: core20
confinement: strict
grade: stable

apps:
  client:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 
      
parts:
  client:
    plugin: python
    source: .

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
