# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: ctrlx-go-appdata
version: '1.0.0'
summary: Application data sample written in go for ctrlX
description: |
  This sample demonstrates how to persist your application data in ctrlX environment
grade: stable
confinement: strict

apps:
  app:
    command: ./bin/appdata .
    plugs:
      - network
      - network-bind
      - network-status
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s 

parts:
  app:
    source: .
    plugin: go
    
  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/    
      
slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
      
  package-run:
    interface: content
    content: package-run
    source:
      write:
      - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}

plugs:
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions
