# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-alldata
version: "2.1.0"
grade: stable
summary: SDK sample app in cpp - provides Data Layer nodes with different data types
description: |
  This app provides two Data Layer branches, each branch initialy has nodes with all simple data types and one flatbuffers type.
  The 'static' branch allows only read access. 
  The 'dynamic' branch allows read and write access of each node.
  Furthermore nodes can be added.
title: sdk-cpp-alldata
base: core20
confinement: strict

# define how apps & services are exposed to host system
apps:
  allDataProvider:
    command: allDataProvider
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs: 
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 

parts:
  alldataprovider:
    plugin: dump
    source: ./generated/build
    stage-packages:
      - libzmq5

  flatbuffers:
    plugin: dump
    source: ./bfbs
  
  deb:
    plugin: dump
    source: ./tmp/ctrlx-datalayer.deb
    source-type: deb
    stage-packages:
      - libzmq5
    override-pull: |
      mkdir -p ../../../tmp/
      cp ../../../../../deb/ctrlx-datalayer-1.*.*.deb ../../../tmp/ctrlx-datalayer.deb
      snapcraftctl pull
    override-prime: |
      rm -rf ../tmp
      snapcraftctl prime


# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
