# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-registernode
version: "2.0.0"
grade: stable
summary: Sample app in cpp to register a Data Layer branch with several nodes
description: |
  This app will create a Data Layer branch 'sdk-cpp-registernode' with node of different data types.
base: core20
confinement: strict

# define how apps & services are exposed to host system
apps:
  registerNode:
    command: registerNode
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 

parts:
  registernode:
    plugin: dump
    source: ./generated/build

  flatbuffers:
    plugin: dump
    source: ./bfbs

  deb:
    plugin: dump
    source: ../../deb/ctrlx-datalayer-1.7.5.deb

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
