name: sdk-py-remote-debug
version: 2.1.0
summary: Data Layer client sample written in Python enables remote debugging on a ctrlX
title: sdk-py-remote-debug
description: |
  The sample demonstrates how remote debugging on a ctrlX can be done. 
base: core20
confinement: strict
grade: stable

apps:
  app:
    command: bin/main.py
    plugs:
     - network
     - network-bind
     - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 
      
parts:
  app:
    plugin: python
    source: .

  datalayerdeb:
      plugin: dump
      source: ./tmp/ctrlx-datalayer.deb
      source-type: deb
      stage-packages:
        - libzmq5
      override-pull: |
        mkdir -p ../../../tmp/
        cp ../../../../../deb/ctrlx-datalayer-1.*.*.deb ../../../tmp/ctrlx-datalayer.deb
        snapcraftctl pull
      override-prime: |
        rm -rf ../tmp
        snapcraftctl prime

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
