# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference
version: '1.0.0'
name: ctrlx-dotnet-logbook
summary: Logbook sample written in .NET for ctrlX.
description: |
  Programm is logging messages to the logbook of ctrlX.
confinement: strict 
#confinement: devmode 
#icon: assets/icons/ICONHERE.png
grade: stable  # must be 'stable' to release into candidate/stable channels
base: core18
type: app

apps:
  app:
    command: diagnostics.logbook
    daemon: simple
    restart-condition: always
    passthrough:   
      restart-delay: 10s
    
    environment:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 'true'
 
parts:
  app:
    plugin: dump
    source: ./generated
